DROP TABLE IF EXISTS tbl;

CREATE TEMPORARY TABLE tbl AS (SELECT t1.num + t2.Num * 10 + t3.num * 100 + 1 AS TableId
FROM 
(
SELECT 0 AS num
UNION ALL
SELECT 1
UNION ALL
SELECT 2
UNION ALL
SELECT 3
UNION ALL
SELECT 4
UNION ALL
SELECT 5
UNION ALL
SELECT 6
UNION ALL
SELECT 7
UNION ALL
SELECT 8
UNION ALL
SELECT 9
) AS t1
CROSS JOIN 
(
SELECT 0 AS num
UNION ALL
SELECT 1
UNION ALL
SELECT 2
UNION ALL
SELECT 3
UNION ALL
SELECT 4
UNION ALL
SELECT 5
UNION ALL
SELECT 6
UNION ALL
SELECT 7
UNION ALL
SELECT 8
UNION ALL
SELECT 9
) AS t2
CROSS JOIN 
(
SELECT 0 AS num
UNION ALL
SELECT 1
UNION ALL
SELECT 2
UNION ALL
SELECT 3
UNION ALL
SELECT 4
UNION ALL
SELECT 5
UNION ALL
SELECT 6
UNION ALL
SELECT 7
UNION ALL
SELECT 8
UNION ALL
SELECT 9
) AS t3);
DELETE FROM multiref_credprogr_Dokumenty_podtv_dohod WHERE ((TableID >=24 AND TableID <=26)); 
INSERT INTO multiref_credprogr_Dokumenty_podtv_dohod SELECT TableIDs.TableID, RefIDs.RefID FROM 
tbl AS TableIDs INNER JOIN
	multiref_credprogr_Dokumenty_podtv_dohod AS RefIds ON RefIds.TableID = 23 
AND ((TableIDs.TableID >=24 AND TableIDs.TableID <=26))  